# Generated by Django 4.2.7 on 2025-11-20 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_report', 'New Animal Report'), ('adoption_request', 'Adoption Request'), ('report_update', 'Report Update')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adoption_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='rescue.adoptionrequest')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='rescue.report')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='rescue.shelter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
